// Command kev-gen regenerates internal/kev/catalog/cisa.yaml from CISA's
// published Known Exploited Vulnerabilities feed.
//
// The catalog is generated rather than hand-maintained because it is a
// transcription, not a judgement: every record is CISA's, and the only
// decisions here are which fields to keep and how to order them. Keeping it
// mechanical is what lets the file be refreshed on a schedule and reviewed as
// a diff — CISA adds entries several times a week, and a catalog nobody can
// cheaply regenerate is a catalog that goes stale, which for this overlay means
// silently UNDER-reporting exploitation.
//
// Four fields survive: the CVE id, the date CISA added it, the BOD 22-01 due
// date, and whether CISA has observed ransomware use. The prose fields
// (vulnerabilityName, shortDescription, requiredAction, notes) are dropped —
// they describe the vendor product CISA cataloged, which is not necessarily
// the package AIROM matched, and printing one next to the other would invite
// exactly the wrong inference.
//
// Run via: go run ./tools/kev-gen
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// feedURL is CISA's canonical JSON feed.
const feedURL = "https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json"

// maxFeed bounds the download. The feed is ~1.8 MB at 1730 entries; 64 MB is
// "something is very wrong" rather than "the catalog grew".
const maxFeed = 64 << 20

type feed struct {
	Title          string `json:"title"`
	CatalogVersion string `json:"catalogVersion"`
	DateReleased   string `json:"dateReleased"`
	Count          int    `json:"count"`
	Vulns          []struct {
		CVEID      string `json:"cveID"`
		DateAdded  string `json:"dateAdded"`
		DueDate    string `json:"dueDate"`
		Ransomware string `json:"knownRansomwareCampaignUse"`
	} `json:"vulnerabilities"`
}

func main() {
	out := flag.String("out", filepath.Join("internal", "kev", "catalog", "cisa.yaml"), "catalog path to write")
	src := flag.String("url", feedURL, "KEV feed URL")
	from := flag.String("file", "", "read the feed from this file instead of the network")
	flag.Parse()

	if err := run(*src, *from, *out); err != nil {
		log.Fatalf("kev-gen: %v", err)
	}
}

func run(url, file, out string) error {
	raw, err := fetch(url, file)
	if err != nil {
		return err
	}
	var f feed
	if err := json.Unmarshal(raw, &f); err != nil {
		return fmt.Errorf("decode feed: %w", err)
	}
	if len(f.Vulns) == 0 {
		return fmt.Errorf("feed carries no vulnerabilities; refusing to write an empty catalog")
	}
	// A count that disagrees with the array means the feed is truncated or the
	// shape changed. Writing it anyway would quietly shrink the catalog, which
	// is the one failure this overlay must not have.
	if f.Count != 0 && f.Count != len(f.Vulns) {
		return fmt.Errorf("feed count %d disagrees with %d entries: refusing a possibly truncated catalog", f.Count, len(f.Vulns))
	}

	type rec struct {
		id, added, due string
		ransomware     bool
	}
	seen := map[string]bool{}
	recs := make([]rec, 0, len(f.Vulns))
	for _, v := range f.Vulns {
		if v.CVEID == "" || v.DateAdded == "" {
			return fmt.Errorf("entry %q has no id or no dateAdded: the feed shape changed", v.CVEID)
		}
		if seen[v.CVEID] {
			continue // CISA has not shipped a duplicate, but a merge upstream could
		}
		seen[v.CVEID] = true
		recs = append(recs, rec{
			id: v.CVEID, added: v.DateAdded, due: v.DueDate,
			// "Known" is the only positive value; "Unknown" is an absence of
			// evidence, not evidence of absence, so it is not represented.
			ransomware: strings.EqualFold(v.Ransomware, "Known"),
		})
	}
	// Sorted by id so a refresh produces a reviewable diff: new entries land in
	// place rather than shuffling the file.
	sort.Slice(recs, func(i, j int) bool { return recs[i].id < recs[j].id })

	var b strings.Builder
	fmt.Fprintf(&b, `# catalog/cisa.yaml — CISA Known Exploited Vulnerabilities.
#
# GENERATED by tools/kev-gen from CISA's published feed. Do not hand-edit: the
# records are a transcription, and the generator is what keeps them one.
#
#   go run ./tools/kev-gen
#
# A CVE absent from this file gets NO KEV record. That is "CISA does not list
# it", which is not the same as "not exploited" — and a stale catalog says it
# about CVEs that were added after the catalog was built, so the refresh
# cadence is part of the claim. EnrichmentStats.CVE.KEVCatalog records which
# catalog actually answered.
source: %s
catalogVersion: %q
released: %s
generated: %s
count: %d
vulnerabilities:
`, feedURL, f.CatalogVersion, day(f.DateReleased), time.Now().UTC().Format("2006-01-02"), len(recs))

	for _, r := range recs {
		fmt.Fprintf(&b, "  - id: %s\n    added: %s\n", r.id, r.added)
		if r.due != "" {
			fmt.Fprintf(&b, "    due: %s\n", r.due)
		}
		if r.ransomware {
			b.WriteString("    ransomware: true\n")
		}
	}

	if err := os.MkdirAll(filepath.Dir(out), 0o750); err != nil {
		return err
	}
	if err := os.WriteFile(out, []byte(b.String()), 0o600); err != nil {
		return err
	}
	fmt.Printf("kev-gen: wrote %s (%d entries, catalog %s released %s)\n", out, len(recs), f.CatalogVersion, day(f.DateReleased))
	return nil
}

// fetch reads the feed from disk when -file is given, else over HTTPS.
func fetch(url, file string) ([]byte, error) {
	if file != "" {
		return os.ReadFile(file) // #nosec G304 -- operator-supplied path
	}
	req, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	client := &http.Client{Timeout: 60 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("fetch %s: %w", url, err)
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("fetch %s: %s", url, resp.Status)
	}
	return io.ReadAll(io.LimitReader(resp.Body, maxFeed))
}

// day trims CISA's RFC3339-ish dateReleased to its calendar day.
func day(s string) string {
	if i := strings.IndexByte(s, 'T'); i > 0 {
		return s[:i]
	}
	return s
}
